import type { Metadata } from "next"
import { barlow } from "./ui/fonts"
import "./globals.css"
import Navbar from "./ui/navbar/navbar"

export const metadata: Metadata = {
  title: "Space Tourism",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${barlow.className} bg-black text-white lg:overflow-y-hidden`}
      >
        <div className="relative">
          <Navbar />
          <>{children}</>
        </div>
      </body>
    </html>
  )
}
